Fix Com memory leak with headers.
jasonsandlin/cpprestsdk pull request #10
Opened 2017-05-30 16:59 UTC by claytonv

Fixes a memory leak with a COM string in the GetAllHeaders function

2017-05-30 19:36 UTC, jasonsandlin requested changes

2017-05-30 19:36 UTC, jasonsandlin commented on Release/src/http/client/http_client_winrt.cpp
> +		if (SUCCEEDED(hr))
tabs -> spaces

2017-05-30 19:36 UTC, jasonsandlin commented on Release/src/http/client/http_client_winrt.cpp
> +		if (SUCCEEDED(hr))
The best thing is for you to submit this as a pull request to https://github.com/Microsoft/cpprestsdk and get them to take it first, then I'll just cherry pick that commit.

2017-05-30 19:36 UTC, jasonsandlin commented on Release/src/http/client/http_client_winrt.cpp
> +		if (SUCCEEDED(hr))
But beyond that, the fix looks good to me

2017-06-16 16:30 UTC, claytonv commented on Release/src/http/client/http_client_winrt.cpp
> +		if (SUCCEEDED(hr))
this was committed to that repo on October 2016 in commit 2b573f4544c228ae14ed0a58fb133c70091c588b. I copied it directly from there. Feel free to cherry pick that though.

2017-06-24 00:19 UTC, jasonsandlin commented on Release/src/http/client/http_client_winrt.cpp
> +		if (SUCCEEDED(hr))
Thanks.  Merged in that commit & closing this PR

2017-06-24 00:20 UTC, closed without merging